[supervisord]
nodaemon=true

[program:docker]
command=/usr/bin/dockerd
priority=10
autorestart=true

[program:jenkins]
command=/usr/bin/java -jar /usr/share/jenkins.war
directory=/var/jenkins_home
user=jenkins
priority=20
autorestart=true
