- name: Lab K8s Deploy
  hosts: k8lab
  tasks:
    - name: Software Installation
      tags: Softwares
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      loop:
        - podman
        - minikube
        - jenkins
        - kubernetes-cli
